name: Bug Report
description: Report a bug to help us improve Supmap
title: "[BUG] <short description>"
labels: [bug]

body:
  - type: markdown
    attributes:
      value: |
        ## 🐞 Bug Report

        Please fill out the information below to help us resolve your issue faster.

  - type: input
    id: environment
    attributes:
      label: Environment
      description: |
        What environment are you seeing the bug in?
        (e.g. Android app, Web dashboard, Backend API, etc.)
      placeholder: ex. Android app, Web dashboard, Backend API
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Please describe the bug clearly and concisely.
      placeholder: What happened? What did you expect to happen?
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce the bug?
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs/Screenshots
      description: Please copy and paste any relevant log output or screenshots.
      placeholder: Paste logs or drag & drop screenshots here.
    validations:
      required: false

  - type: input
    id: version
    attributes:
      label: App/Service Version
      description: What version of the app/service are you using?
      placeholder: ex. v1.2.3, commit hash, etc.
    validations:
      required: false

  - type: dropdown
    id: os
    attributes:
      label: Operating System
      description: What OS are you using?
      options:
        - Android
        - iOS
        - Windows
        - macOS
        - Linux
        - Other
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here.
    validations:
      required: false
