name: Feature Request
description: Suggest a new feature or improvement for Supmap
title: "[FEATURE] <short description>"
labels: [enhancement]

body:
  - type: markdown
    attributes:
      value: |
        ## 🚀 Feature Request

        Thank you for taking the time to suggest a feature! Please fill out the details below.

  - type: input
    id: summary
    attributes:
      label: Feature Summary
      description: Briefly describe the feature or improvement you are requesting.
      placeholder: ex. Add dark mode to the mobile app
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation
      description: Why do you want this feature? What problem does it solve or what value does it add?
      placeholder: ex. It would make the app easier to use at night.
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed Solution
      description: How do you imagine this feature working? (If you have a specific idea, describe it here.)
      placeholder: ex. Add a toggle in settings to switch between light and dark mode.
    validations:
      required: false

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Did you consider any alternative solutions or features?
      placeholder: ex. Use the system theme instead of a manual toggle.
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or mockups about the feature request here.
    validations:
      required: false
